// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHi5i-DMBTAzIy-MVeYn72vobcngQ1DPo',
    appId: '1:668259295968:web:ca02b18825afe58e0da685',
    messagingSenderId: '668259295968',
    projectId: 'carpi-rehab',
    authDomain: 'carpi-rehab.firebaseapp.com',
    storageBucket: 'carpi-rehab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl9vTqPw-HShjOsLCKFswTXYVwV8Od-RY',
    appId: '1:668259295968:android:d7dede2d5e2e309a0da685',
    messagingSenderId: '668259295968',
    projectId: 'carpi-rehab',
    storageBucket: 'carpi-rehab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbHl-uScaKNDt1U0HLF5x1l6p4cUE9HQ',
    appId: '1:668259295968:ios:52ddeb4ce52fafc70da685',
    messagingSenderId: '668259295968',
    projectId: 'carpi-rehab',
    storageBucket: 'carpi-rehab.appspot.com',
    iosClientId: '668259295968-svl4fq7c94s46ng2g8ft6bbd71ckbkod.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpiWindowsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLbHl-uScaKNDt1U0HLF5x1l6p4cUE9HQ',
    appId: '1:668259295968:ios:948c3d6bb4751ac70da685',
    messagingSenderId: '668259295968',
    projectId: 'carpi-rehab',
    storageBucket: 'carpi-rehab.appspot.com',
    iosClientId: '668259295968-33koic9lhplobur6gngpa0fehdilr37u.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpiWindowsApp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHi5i-DMBTAzIy-MVeYn72vobcngQ1DPo',
    appId: '1:668259295968:web:11f77bf0a3931d620da685',
    messagingSenderId: '668259295968',
    projectId: 'carpi-rehab',
    authDomain: 'carpi-rehab.firebaseapp.com',
    storageBucket: 'carpi-rehab.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAHi5i-DMBTAzIy-MVeYn72vobcngQ1DPo',
    appId: '1:668259295968:web:215538bb8d1057970da685',
    messagingSenderId: '668259295968',
    projectId: 'carpi-rehab',
    authDomain: 'carpi-rehab.firebaseapp.com',
    storageBucket: 'carpi-rehab.appspot.com',
  );
}
